version: '3.8'

services:
  ehr-frontend:
    container_name: ehr-frontend
    build: .
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_BACKEND_URL=http://localhost:3001/api
    volumes:
      - .:/app
      - /app/node_modules
    restart: unless-stopped
